FROM ubuntu:15.10

WORKDIR /gauntlt

ADD . . 

RUN apt-get update && \
	apt-get install -y --no-install-recommends apt-utils software-properties-common && \
	DEBIAN_FRONTEND=noninteractive apt-add-repository ppa:brightbox/ruby-ng && \
	apt-get update && apt-get install -y git ruby2.2 ruby2.2-dev build-essential libz-dev libcurl4-gnutls-dev python-software-properties libcurl4-gnutls-dev python-dev python-pip nmap bundler build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 wget libfontconfig1-dev bundler sqlmap

RUN gem install gauntlt && \
RUN	pip install --upgrade setuptools && \
	pip install sslyze && \
	pip install typing 
	

RUN git clone https://github.com/freddyb/Garmr.git && \
	pip install requests && \
	pip install BeautifulSoup && \
	cd Garmr && \
	python setup.py install